- name: Run setup script on remote server
  hosts: "{{ ssh_host }}"
  become: yes  # If you need sudo privileges to run the script
  tasks:
    - name: Debug environment variables
      debug:
        msg:
          - "SSH_USER: {{ ssh_user }}"
          - "SSH_HOST: {{ ssh_host }}"
          
    - name: Ensure /opt/runai directory exists
      file:
        path: /opt/runai
        state: directory
        mode: '0755'

    - name: Copy setup.sh to the remote server
      copy:
        src: ../scripts/setup.sh  # Copy the setup.sh script from your repo
        dest: /opt/runai/setup.sh
        mode: '0755'

    - name: Execute the setup.sh script and log the output
      shell: |
        /opt/runai/setup.sh > /opt/runai/output_setup.txt 2>&1
      register: setup_output
      ignore_errors: yes

    - name: Store the output of the script in a log file
      copy:
        content: "{{ setup_output.stdout }}"
        dest: /opt/runai/output_setup.txt
        mode: '0644'
