---
- name: Run setup script on remote server
  hosts: all
  become: yes  # If you need sudo privileges to run the script
  tasks:
    - name: Debug SSH_PRIVATE_KEY variable
      debug:
        msg: "SSH private key from environment: {{ lookup('env', 'SSH_PRIVATE_KEY') }}"

    - name: Debug SSH_USER and SSH_HOST
      debug:
        msg:
          - "SSH_USER: {{ lookup('env', 'SSH_USER') }}"
          - "SSH_HOST: {{ lookup('env', 'SSH_HOST') }}"

    - name: Create a temporary file for the private key
      copy:
        content: "{{ lookup('env', 'SSH_PRIVATE_KEY') }}"  # Copy private key to a temp file
        dest: /tmp/private_key
        mode: '0600'

    - name: Copy setup.sh to the remote server
      copy:
        src: ../scripts/setup.sh  # Copy the setup.sh script from your repo
        dest: /tmp/setup.sh
        mode: '0755'

    - name: Execute the setup.sh script
      command: /tmp/setup.sh
