name: Run Setup Script

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest  # This will use an Ubuntu environment

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the repository to the runner

      # Set up SSH agent for authentication with the remote server
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key.pem  # Corrected the private key filename
          chmod 600 ~/.ssh/private_key.pem  # Ensure the private key has the correct permissions

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml \
            -i $SSH_HOST, \  # Ensure $SSH_HOST is a valid IP or hostname (add a comma)
            --private-key ~/.ssh/private_key.pem \
            --user $SSH_USER
        env:
          SSH_USER: ${{ secrets.SSH_USER }}  # GitHub Secret for SSH user
          SSH_HOST: ${{ secrets.SSH_HOST }}  # GitHub Secret for SSH host
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secret for SSH private key
