name: Run Setup Script

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest  # This will use an Ubuntu environment

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the repository to the runner

      # Set up SSH agent for authentication with the remote server
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Set environment variables for Ansible
      - name: Set up environment variables for Ansible
        run: |
          echo "SSH_USER=${{ secrets.SSH_USER }}" >> $GITHUB_ENV
          echo "SSH_HOST=${{ secrets.SSH_HOST }}" >> $GITHUB_ENV

      # Debug the environment variables in the context of the Ansible playbook
      - name: Debug environment variables in Ansible
        run: |
          echo "Environment Variables:"
          echo "SSH_USER=${{ secrets.SSH_USER }}"
          echo "SSH_HOST=${{ secrets.SSH_HOST }}"

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.SSH_USER }}
          ANSIBLE_HOST: ${{ secrets.SSH_HOST }}
          ANSIBLE_HOST_KEY_CHECKING: False  # Disables SSH host key checking
        run: |
          ansible-playbook ansible/playbook.yml --private-key private_key.pem -u ${{ secrets.SSH_USER }} \
          -e ssh_host=${{ secrets.SSH_HOST }} -e ssh_user=${{ secrets.SSH_USER }}
